export const CHANGE_ROOMID_FILTER_HAS_PAYLOAD = "CHANGE_ROOMID_FILTER_HAS_PAYLOAD";
export const CHANGE_ROOMID_FILTER_HAS_PAYLOAD_REQ = "CHANGE_ROOMID_FILTER_HAS_PAYLOAD_REQ";

export const CHANGE_DATE_FILTER_HAS_PAYLOAD = "CHANGE_DATE_FILTER_HAS_PAYLOAD";
export const CHANGE_DATE_FILTER_HAS_PAYLOAD_REQ = "CHANGE_DATE_FILTER_HAS_PAYLOAD_REQ";